name: CI 

on:
  push:

jobs:
  run-biome-and-jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set current datetime as env variable
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Show current datetime
      run: echo ${{ env.CURRENT_DATETIME }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn install

    - name: Check format
      run: yarn biome format

    - name: Check Lint
      run: yarn biome check
  
    - name: Test
      run: yarn test
